springdoc:
  api-docs:
    groups:
      enable: true
    path: "/ospo-metrics/openapi/v3/api-docs"
  swagger-ui:
    path: "/ospo-metrics/openapi/swagger-ui.html"
server:
  port: 8080
spring:
  application:
    name: "OSPOMetrics"
  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
#    host: "b-0dce7389-10b8-4035-b0e2-1716eabcbd9d.mq.us-east-1.amazonaws.com"
#    username: "mqadminusr"
#    password: "XIw{Y&jxT#2Y.b4"
adapter:
  elasticconsumer:
    timeout: 60000
    url: "http://localhost:9200"
#    url: "https://vpc-ospo-metrics-osd-dev-pojn4dii3he6abi366eevg6bb4.us-east-1.es.amazonaws.com"
  azureconsumer:
    timeout: 60000
  restconsumer:
    github:
      url: "https://api.github.com"
      timeout: 60000
      mimeType: "application/vnd.github.v3+json"
      userAgentName: "bancolombia"
      token:
        issuer: "138960"
        installID: "19566378"
        expiredAfter: 3600
aws:
  secret:
#    opensearch: "ospo-metrics-opensearch-secret-dev"
#    github: "ospo-metrics-key-rsa-secret-dev"
#    metric: "ospo-metrics-cnx-rds-secret-dev"
#    azure-security: "ospo-metrics-azure-secret-dev"
#    amazon-mq: "ospo-metrics-user-amazon-mq-secret-dev"
    opensearch: "ospo-metrics-opensearch-secret-local"
    github: "ospo-metrics-key-rsa-secret-local"
    metric: "ospo-metrics-cnx-rds-secret-local"
    azure-security: "ospo-metrics-azure-secret-local"
    amazon-mq: "ospo-metrics-user-amazon-mq-secret-local"
commons:
  jms:
    input-concurrency: 10
    input-queue: "DEV.QUEUE.2"
    input-queue-alias: ""
    reactive: true
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
