apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: #{service-name}#-hpa-#{version}#
  namespace: #{namespace}#
  labels:
    app.bancolombia.com.co/env: "#{env}#"
    app.bancolombia.com.co/cost-center: "#{cost-center}#"
    app.bancolombia.com.co/application-code: "#{application-code}#"
    app.bancolombia.com.co/project-name: "#{projectname}#"
    app.bancolombia.com.co/pmo: "#{pmo}#"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{service-name}#-deployment
  minReplicas: #{min-replicas}#
  maxReplicas: #{max-replicas}#
  #targetCPUUtilizationPercentage: #{hpa-targetCPU}#
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: #{hpa-cpu}#
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: #{hpa-memory}#
#status:
#  currentReplicas: #{replicas}#
#  desiredReplicas: #{replicas}#
